name: assistant sdk build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and test assistant sdk
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          scheme: ${{ 'assistant sdk' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild -scheme "$scheme" -sdk iphonesimulator
      - name: Test
        env:
          scheme: ${{ 'assistant sdk' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild test-without-building -scheme "$scheme" -destination "platform=$platform,name=iPhone 11"
