name: assistant sdk build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show Devices
        run: | 
          xcrun xctrace list devices
      - name: Build
        env:
          scheme: ${{ 'assistant sdk' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild -scheme "$scheme" -destination "platform=iOS Simulator,name=iPhone 11"
      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          xcodebuild test-without-building -scheme "$scheme" -destination "platform=iOS Simulator,name=iPhone 11"
